[package]
name = "math-parser"
version = "0.3.0"
authors = ["FinGu"]
edition = "2018"

[lib]
name = "mp"
path = "src/lib.rs"

[[example]]
name="clicalc"
path = "examples/clicalc.rs"

[dev-dependencies]
clap = "2.33.3"
